src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nomUser;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $prenomUser;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ddnUser;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $emailUser;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Roles", inversedBy="UserRole")
     */
    private $TypeRole;

    public function getId(): int
    {
        return $this->id;
    }

    public function isGranted($role='ROLE_USER')
    {
        return (is_null($role)?'NO':in_array($role,$this->getTypeRole()));
    }

    /**
     * @return (Role|string)[] The user roles
     */

    public function getRoles()
    {
        return ['ROLE_ADMIN']; // (is_null($this->TypeRole)?['ROLE_USER']:$this->TypeRole);
    }

    /**
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->password
        ]);
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        return list($this->id,
            $this->username,
            $this->password) = unserialize($serialized, ['allowed_class'=>false]);
    }

    /**
     * Removes sensitive data from the user.
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
    }

    public function getNomUser(): ?string
    {
        return $this->nomUser;
    }

    public function setNomUser(?string $nomUser): self
    {
        $this->nomUser = $nomUser;

        return $this;
    }

    public function getPrenomUser(): ?string
    {
        return $this->prenomUser;
    }

    public function setPrenomUser(?string $prenomUser): self
    {
        $this->prenomUser = $prenomUser;

        return $this;
    }

    public function getDdnUser(): ?\DateTimeInterface
    {
        return $this->ddnUser;
    }

    public function setDdnUser(?\DateTimeInterface $ddnUser): self
    {
        $this->ddnUser = $ddnUser;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmailUser(): ?string
    {
        return $this->emailUser;
    }

    public function setEmailUser(string $emailUser): self
    {
        $this->emailUser = $emailUser;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getTypeRole(): ?Roles
    {
        return $this->TypeRole;
    }

    public function setTypeRole(?Roles $TypeRole): self
    {
        $this->TypeRole = $TypeRole;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Bienvenue{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://bootswatch.com/_assets/css/custom.min.css">
            <link rel="stylesheet" href="https://cdn.datatables.net/1.10.6/css/jquery.dataTables.min.css" />
            <!-- <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.css">-->
            <link rel="stylesheet" href="https://bootswatch.com/4/superhero/bootstrap.css">
            <style>
                .sans_marges    {   margin-left: 0px;
                                    margin-right: 0px;
                                    margin-top : 0px;
                                    margin-bottom: 0px; }
                .bord_rouge     {   border : 1px;
                                    border-color: darkred;
                                    border-style: solid;}
                .bord_bleu      {   border : 1px;
                                    border-color: dodgerblue;
                                    border-style: solid;}
                .bord_gauche    {   border-left : 1px;
                                    border-left-style: solid;}
                .bord_gris_clair{   border : 1px;
                                    border-color: lightslategray;
                                    border-style: dashed;}
                .btn-petit      {   font-size: 9px; padding: 5px 12px;}
                .arrondi        {   border-radius: 8px;}
                .rond           {   border-radius: 50%;}
                .btn-trans      {   -webkit-transition-duration: 0.4s; /* Safari */
                                    transition-duration: 0.4s;}
            </style>
        {% endblock %}
    </head>
    <body>
        <div class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
            <!-- is_granted("ROLE_ADMIN") -->
            <a class="navbar-brand" href="{{ path('home') }}">Ash Studio {% if app.user.typeRole is defined %} <small>{{ app.user.typeRole.nomRole  }}</small>{% endif %}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if rubrique is defined and rubrique=='INDEX' %}active{% endif %}"
                           href="{{ path('ash_studio') }}">Mes créations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if rubrique is defined and rubrique=='PANIER' %}active{% endif %}"
                           href="#panier">Mon panier</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if app.user.typeRole is defined and app.user.typeRole.id > 1 %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Interface de gestion</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item {% if rubrique is defined and rubrique=='NEW' %}active{% endif %}"
                                   href="{{ path('creation_admin') }}">Gérer les créations</a>
                                <a class="dropdown-item {% if rubrique is defined and rubrique=='NEW_MATIERE' %}active{% endif %}"
                                   href="{{ path('matiere_admin') }}">Gérer les matières</a>
                                {% if app.user.typeRole.nomRole == 'SUPER_ADMIN' %}
                                    <a class="dropdown-item {% if rubrique is defined and rubrique=='NEW_USER' %}active{% endif %}"
                                       href="{{ path('user_index') }}">Gérer les utilisateurs</a>
                                    <a class="dropdown-item {% if rubrique is defined and rubrique=='NEW_USER' %}active{% endif %}"
                                       href="{{ path('roles_index') }}">Gérer les roles</a>
                                {% endif %}
                            </div>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        {% if app.user %}
                            <a href="{{ path('app_logout') }}" class="nav-link">Se déconnecter</a>
                        {% else %}
                            <!--<a href="#" id="btn_modal" class="nav-link" data-toggle="modal" data-target="#myModal">Se connecter</a>-->
                            <a href="{{ path('login') }}" id="btn_modal" class="nav-link">Se connecter</a>
                        {% endif %}
                    </li>

                </ul>
            </div>
        </div>
        {% include '/security/modal.html.twig' %}
        {% block body %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"
                integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        {% block javascripts %}
            <script type="text/javascript">
                $(document).ready(function()
                {
                    $(".alert").delay(3000).slideUp(500);
                    /*$('#btn_modal').click(function ()
                    {
                        console.log('click btn_modal');
                        //Afficher Le titre de popup
                        var url = '{{ path('login') }}';
                        $.ajax({
                             type: 'post',
                             url: url,
                             success: function (code_html, status)
                             {
                                 alert('success'+'\n'+code_html);
                                 $('#btn_valid_login_form').click(function ()
                                 {
                                     var data = $("[name='post']").serialize();
                                     $.ajax({
                                         type: 'post',
                                         url: '{{ path('login') }}',
                                         data: data
                                     });
                                    $('#myModal').modal("hide");
                                 });
                                 // $('#modal_detail').html(data);
                                 //Affichage de nouvelle popup
                             }
                         });
                    });/**/
                });
            </script>
            {% endblock %}
    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div id="calendar-holder"></div>
    <div class="jumbotron">
        <div class="container">
            <h1>Charlotte Ash Studio</h1>
        </div>
    </div>
    <div class="container">
        <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores aspernatur cumque debitis distinctio dolorem doloribus ducimus, itaque maxime neque, optio porro quo veniam! Amet consequuntur ea ipsum modi similique!</span><span>Ad adipisci autem debitis dicta dolorem ea est fugiat labore libero magnam maiores molestiae odio officia optio perspiciatis recusandae reiciendis sapiente suscipit, tenetur totam ut vel veniam. Eaque, incidunt veniam.</span><span>Animi culpa debitis dicta ducimus error itaque nam quae similique! Atque, et excepturi ipsam minus omnis quis velit. Ad amet animi enim eos iste maiores, officiis pariatur quod saepe veritatis.</span><span>Alias assumenda commodi consectetur corporis dignissimos eius eveniet fugiat incidunt iure laboriosam nesciunt nihil nobis nulla possimus provident quisquam ratione recusandae repellat sint, veniam! Aliquid dicta iste itaque laborum quas.</span></p>
    </div>
{% endblock %}